CREATE TABLE tag (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL
);

CREATE TABLE task (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	"start" TIMESTAMP WITH TIME ZONE,
	"end" TIMESTAMP WITH TIME ZONE
);

CREATE INDEX task_start_idx ON task("start");

CREATE TABLE task_tag (
	tag_id INTEGER REFERENCES tag(id) ON DELETE CASCADE,
	task_id INTEGER REFERENCES task(id) ON DELETE CASCADE
);
