CREATE TABLE tag (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL UNIQUE
);

CREATE TABLE task (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	"start" TIMESTAMP WITH TIME ZONE UNIQUE,
	"end" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE task_tag (
	tag_id INTEGER REFERENCES tag(id) ON DELETE CASCADE,
	task_id INTEGER REFERENCES task(id) ON DELETE CASCADE,
	PRIMARY KEY(tag_id, task_id)
);
